import { InteriorCategory } from './../../interfaces/card.interface';

export const InteriorCategoryFake: Array<InteriorCategory> = [
    {
        "interiorCategoryId": 1,
        "categoryId": 2,
        "subCategoryId": 1,
        "name": "Listing",
        "displayStatus": 0,
        "icon": "https://gmbb20.s3.amazonaws.com/Interior/Captura+de+pantalla+2023-09-26+111128.png",
        "categoryLandPageDesc": null,
        "categoryLandPageHead": null,
        "subCategoryLandPageDesc": null,
        "isActive": false,
        "seotitle": null,
        "seoprettyUrl": null,
        "seodescMetadata": null,
        "createdDate": "2023-09-26T18:21:26.28",
        "updatedDate": "2023-09-26T18:21:26.28",
        "deleteFlag": false,
        "rowVersion": "AAAAAAAAB9E="
    },
    {
        "interiorCategoryId": 2,
        "categoryId": 2,
        "subCategoryId": 1,
        "name": "Open House",
        "displayStatus": 0,
        "icon": "https://gmbb20.s3.amazonaws.com/Interior/openhouse.jpg",
        "categoryLandPageDesc": null,
        "categoryLandPageHead": null,
        "subCategoryLandPageDesc": null,
        "isActive": false,
        "seotitle": null,
        "seoprettyUrl": null,
        "seodescMetadata": null,
        "createdDate": "2023-09-26T18:22:09.3433333",
        "updatedDate": "2023-09-26T18:22:09.3433333",
        "deleteFlag": false,
        "rowVersion": "AAAAAAAAB9I="
    },
    {
        "interiorCategoryId": 1,
        "categoryId": 2,
        "subCategoryId": 1,
        "name": "Listing",
        "displayStatus": 0,
        "icon": "https://gmbb20.s3.amazonaws.com/Interior/Captura+de+pantalla+2023-09-26+111128.png",
        "categoryLandPageDesc": null,
        "categoryLandPageHead": null,
        "subCategoryLandPageDesc": null,
        "isActive": false,
        "seotitle": null,
        "seoprettyUrl": null,
        "seodescMetadata": null,
        "createdDate": "2023-09-26T18:21:26.28",
        "updatedDate": "2023-09-26T18:21:26.28",
        "deleteFlag": false,
        "rowVersion": "AAAAAAAAB9E="
    },
    {
        "interiorCategoryId": 1,
        "categoryId": 2,
        "subCategoryId": 1,
        "name": "Listing",
        "displayStatus": 0,
        "icon": "https://gmbb20.s3.amazonaws.com/Interior/Captura+de+pantalla+2023-09-26+111128.png",
        "categoryLandPageDesc": null,
        "categoryLandPageHead": null,
        "subCategoryLandPageDesc": null,
        "isActive": false,
        "seotitle": null,
        "seoprettyUrl": null,
        "seodescMetadata": null,
        "createdDate": "2023-09-26T18:21:26.28",
        "updatedDate": "2023-09-26T18:21:26.28",
        "deleteFlag": false,
        "rowVersion": "AAAAAAAAB9E="
    },
    {
        "interiorCategoryId": 1,
        "categoryId": 2,
        "subCategoryId": 1,
        "name": "Listing",
        "displayStatus": 0,
        "icon": "https://gmbb20.s3.amazonaws.com/Interior/Captura+de+pantalla+2023-09-26+111128.png",
        "categoryLandPageDesc": null,
        "categoryLandPageHead": null,
        "subCategoryLandPageDesc": null,
        "isActive": false,
        "seotitle": null,
        "seoprettyUrl": null,
        "seodescMetadata": null,
        "createdDate": "2023-09-26T18:21:26.28",
        "updatedDate": "2023-09-26T18:21:26.28",
        "deleteFlag": false,
        "rowVersion": "AAAAAAAAB9E="
    },
    {
        "interiorCategoryId": 1,
        "categoryId": 2,
        "subCategoryId": 1,
        "name": "Listing",
        "displayStatus": 0,
        "icon": "https://gmbb20.s3.amazonaws.com/Interior/Captura+de+pantalla+2023-09-26+111128.png",
        "categoryLandPageDesc": null,
        "categoryLandPageHead": null,
        "subCategoryLandPageDesc": null,
        "isActive": false,
        "seotitle": null,
        "seoprettyUrl": null,
        "seodescMetadata": null,
        "createdDate": "2023-09-26T18:21:26.28",
        "updatedDate": "2023-09-26T18:21:26.28",
        "deleteFlag": false,
        "rowVersion": "AAAAAAAAB9E="
    },
    {
        "interiorCategoryId": 1,
        "categoryId": 2,
        "subCategoryId": 1,
        "name": "Listing",
        "displayStatus": 0,
        "icon": "https://gmbb20.s3.amazonaws.com/Interior/Captura+de+pantalla+2023-09-26+111128.png",
        "categoryLandPageDesc": null,
        "categoryLandPageHead": null,
        "subCategoryLandPageDesc": null,
        "isActive": false,
        "seotitle": null,
        "seoprettyUrl": null,
        "seodescMetadata": null,
        "createdDate": "2023-09-26T18:21:26.28",
        "updatedDate": "2023-09-26T18:21:26.28",
        "deleteFlag": false,
        "rowVersion": "AAAAAAAAB9E="
    },
    {
        "interiorCategoryId": 1,
        "categoryId": 2,
        "subCategoryId": 1,
        "name": "Listing",
        "displayStatus": 0,
        "icon": "https://gmbb20.s3.amazonaws.com/Interior/Captura+de+pantalla+2023-09-26+111128.png",
        "categoryLandPageDesc": null,
        "categoryLandPageHead": null,
        "subCategoryLandPageDesc": null,
        "isActive": false,
        "seotitle": null,
        "seoprettyUrl": null,
        "seodescMetadata": null,
        "createdDate": "2023-09-26T18:21:26.28",
        "updatedDate": "2023-09-26T18:21:26.28",
        "deleteFlag": false,
        "rowVersion": "AAAAAAAAB9E="
    }
]